[build]
  base = "forge web/foxloop"
  command = "npm run build"
  publish = ".next"

[build.processing.html]
  pretty_urls = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/forge-demo.html"
  to = "/forge-demo"
  status = 301
  force = true

[[redirects]]
  from = "/forge-demo"
  to = "/forge-demo.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacypolicy"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/termsandconditions"
  status = 301

[[redirects]]
  from = "/privacypolicy"
  to = "/privacypolicy.html"
  status = 200

[[redirects]]
  from = "/termsandconditions"
  to = "/termsandconditions.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.png"
  status = 200
